### ISSUE TITLE
Consider using a directory instead of files

### ISSUE THREAD

**Issue by chelm** [jseppi/koop-geojson-file#1]
This looks wonderful, but one thing jumps out. The config takes a list of files like so: 

```
 "geojsonFiles": [
    "/data/test-file.geojson"
    "/data/other-file.geojson"
  ]
```

But what about making it just look at directly like: 

```
 "geojsonFiles": "/data/geojson/"
```

Then any file could be added to the directory and Koop would be able to create a feature service from it.

**Comment by jseppi** [comment]
That was actually how I first implemented it (before publishing the repo), but ended up deciding that actual paths would be more flexible. The way we use it is we have several chron'd processes that spit out GeoJSON files to disk in various locations and not necessarily in a shared location so the explicit paths work better for us.

Will keep thinking about it though.

**Comment by chelm** [comment]
Sounds good. I am fan of what you think is best.
