### ISSUE TITLE
Consider dropping the cache completely

### ISSUE THREAD

**Issue by chelm** [jseppi/koop-geojson-file#2]
I think in the case of serving data from the filesystem it makes sense to just not use Koop's cache at all. This way you wouldn't be duplicating the data and will just be reading whats on disk every time... 

One drawback would be that the entire file would need to be unpacked from disk and spatially filtered. I guess that's bad. So maybe using the cache is smart.

**Comment by jseppi** [comment]
Yeah, I was rolling around that idea in my head and decided to keep the cache. The watcher in the GeoJsonFile model invalidates the cache on file change so that the most current version of the file will be used.
