### ISSUE TITLE
Adding ArcMap Support

### ISSUE THREAD

**Issue by rowanwins** [jseppi/koop-geojson-file#6]
Gday @jseppi 

Thanks for a great koop provider, just wondering if you had tried this in ArcMap, I've given it a go but can't seem to get it working?

From what I gather from this [koop issue](https://github.com/koopjs/koop/issues/125) some work needs to be done to make sure the post requests are correctly setup. I'm not sure how easy or difficult this is to get going, I'll have a bit of a play today but if you've got any insight that would be great.

Thanks,
Rowan

**Comment by jseppi** [comment]
Hi Rowan,
You're right, it doesn't work in ArcMap, which is kind of the reason I gave up on koop. I'm not exactly sure what needs to be done, and my reasons for even attempting this are long gone. If you're able to get something working I'll gladly accept a PR.
